# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceConfig',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('value', models.CharField(max_length=200)),
                ('state', models.IntegerField(default='1')),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'interface_config',
                'verbose_name': '\u53c2\u6570\u914d\u7f6e',
                'verbose_name_plural': '\u53c2\u6570\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='InterfaceTestcase1',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('case_id', models.CharField(max_length=45, unique=True)),
                ('case_name', models.CharField(max_length=45)),
                ('request_type', models.CharField(max_length=45)),
                ('url', models.CharField(max_length=100)),
                ('parameters', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, editable=False, null=True)),
                ('status_code', models.CharField(blank=True, editable=False, max_length=5, null=True)),
                ('expected', models.TextField(blank=True, null=True)),
                ('not_expected', models.TextField(blank=True, null=True)),
                ('actual', models.TextField(blank=True, editable=False, null=True)),
                ('config', models.CharField(blank=True, max_length=200, null=True)),
                ('result', models.CharField(blank=True, editable=False, max_length=5, null=True)),
                ('time', models.IntegerField(blank=True, editable=False, null=True)),
                ('state', models.IntegerField(default='1')),
            ],
            options={
                'ordering': ['case_id'],
                'db_table': 'interface_test1',
                'verbose_name': '\u6d4b\u8bd5\u7528\u4f8b',
                'verbose_name_plural': '\u6d4b\u8bd5\u7528\u4f8b',
            },
        ),
    ]
